baseurl = "http://xenidevblog.github.io"
title = "Видеоцитаты"
languageCode = "en-us"
paginate = "10" # Number of posts per page
theme = "amnix"
disqusShortname = "" # Enable comments by entering your Disqus shortname
googleAnalytics = "" # Enable Google Analytics by entering your tracking id

[Params]
  description = "Responsive and configurable Hugo theme" # Site description. Used in meta description
  opengraph = true # Enable OpenGraph
  twitterCards = true # Enable Twitter Cards
  columns = 2 # Set the number of content cards columns. Possible values: 1, 2, 3
  mainSections = ["post"] # Set main page sections
  dateFormat = "January 02, 2006" # Change the format of dates
  customCSS = ["css/custom.css"] # Include custom CSS files
  customJS = ["js/custom.js"] # Include custom JS files
  comments = true # Enable comments for all site pages
  related = true # Enable Related Content (See https://gohugo.io/content-management/related/)
  mathjax = true # Enable MathJax for all site pages
  mathjaxPath = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.6/MathJax.js" # Specify MathJax path. Optional
  mathjaxConfig = "TeX-AMS-MML_HTMLorMML" # Specify MathJax config. Optional

[Params.Featured]
  previewOnly = false # Show only preview featured image

[Params.Sidebar]
  widgets = [ "locations", "tags", "categories","recent"] # Enable sidebar widgets in given order
  position = "right" # Change sidebar position for all site pages: "right", "left" or false
  positionHome = "right" # Change sidebar position for home page
  positionList = "right" # Change sidebar position for list pages
  positionSingle = "right" # Change sidebar position for single pages

[Params.Widgets]
  recentNum = 5 # Set number of articles in the "Recent articles" widget
  recentDate = true # Show datetime in the "Recent Posts" widget
  tagsCounter = true # Enable counter for each tag in the "Tags" widget

[Params.Social] # Site Social block
  email = "example@example.com"
  facebook = "username"
  twitter = "username"
  telegram = "username"
  instagram = "username"
  vk = "username"


[Params.Share] # Post Share block
  facebook = true
  twitter = true
  telegram = true
  vk = true


[Params.Manifest] # Web App Manifest config
  name = "Amnix"
  shortName = "Amnix"
  display = "standalone"
  startUrl = "/"
  backgroundColor = "#33333a"
  themeColor = "#5b5b67"
  description = "Responsive and configurable Hugo theme"
  orientation = "portrait"
  scope = "/"

[outputFormats]
  [outputFormats.MANIFEST] # Add custom MANIFEST output format
    mediaType = "application/json"
    baseName = "manifest"
    isPlainText = true
    notAlternative = true

[outputs]
  home = ["HTML", "RSS", "MANIFEST"] # Include MANIFEST format to home page

  [taxonomies]
  locations = "locations"
  tag = "tags"
  category = "categories"
